author: J. Morgan Lieberthal
github_url: https://github.com/baberthal/ChannelKit

theme: fullwidth
clean: true
min_acl: internal

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false
